export const FRUIT_EMOJIS: Record<string, string> = {
  blueberry: '🫐',
  grape: '🍇',
  lime: '🍋',
  lemon: '🍋',
  peach: '🍑',
  avocado: '🥑',
  banana: '🍌',
  carrot: '🥕',
  coconut: '🥥',
  pineapple: '🍍',
  cantaloupe: '🍈',
  'navel orange': '🍊',
  pear: '🍐',
  grapefruit: '🍊',
  'small watermelon': '🍉',
  'mini watermelon': '🍉',
  'small pumpkin': '🎃',
  papaya: '🥭',
  squash: '🥦',
  'butternut squash': '🥦',
  'kidney bean': '🫘',
  kumquat: '🍊',
  fig: '🫐',
  'sweet pea': '🌱',
  'apple seed': '🌱',
  'sesame seed': '🌱',
  'poppy seed': '🌱',
  'poppyseed cluster': '🌱',
  lentil: '🌱',
  cauliflower: '🥦',
  'romaine lettuce': '🥬',
  'winter melon': '🍈',
  'honeydew melon': '🍈',
  'bell pepper': '🫑',
  'heirloom tomato': '🍅',
  'ear of corn': '🌽',
  'scallion bunch': '🌿',
  rutabaga: '🥔',
};

export function getFruitEmoji(sizeFruit: string): string {
  return FRUIT_EMOJIS[sizeFruit.toLowerCase()] ?? '🌿';
}
